const express=require('express');const fs=require('fs');const path=require('path');const crypto=require('crypto');
const app=express(),PORT=process.env.PORT||8080,DB=path.join(__dirname,'data/db.json'),sessions=new Map();
app.use(express.json());app.use(express.urlencoded({extended:true}));app.use(express.static(path.join(__dirname,'public')));
const read=()=>JSON.parse(fs.readFileSync(DB,'utf8')),write=d=>fs.writeFileSync(DB,JSON.stringify(d,null,2)),id=()=>crypto.randomUUID();
function pwd(p,s){return crypto.scryptSync(p,s,64).toString('hex')}function makePwd(p){let s=crypto.randomBytes(16).toString('hex');return{s,hash:pwd(p,s)}}
function pub(f){let x={...f};delete x.passwordHash;delete x.salt;return x}
function auth(req,res,next){let t=(req.headers.authorization||'').replace('Bearer ','');let db=read(),f=db.farmers.find(x=>x.id===sessions.get(t));if(!f)return res.status(401).json({error:'Please login first.'});req.db=db;req.farmer=f;req.token=t;next()}
app.post('/api/auth/register',(req,res)=>{let {name,phone,email,password,village,district,state}=req.body;if(!name||!phone||!password)return res.status(400).json({error:'Name, phone and password are required.'});if(password.length<6)return res.status(400).json({error:'Password must contain at least 6 characters.'});let db=read();if(db.farmers.some(f=>f.phone===phone))return res.status(409).json({error:'An account with this phone number already exists.'});let q=makePwd(password),f={id:id(),name,phone,email:email||'',village:village||'',district:district||'',state:state||'',salt:q.s,passwordHash:q.hash,createdAt:new Date().toISOString()};db.farmers.push(f);write(db);let token=crypto.randomBytes(32).toString('hex');sessions.set(token,f.id);res.json({token,farmer:pub(f)})});
app.post('/api/auth/login',(req,res)=>{let {phone,password}=req.body,db=read(),f=db.farmers.find(x=>x.phone===phone);if(!f||pwd(password||'',f.salt)!==f.passwordHash)return res.status(401).json({error:'Invalid phone number or password.'});let token=crypto.randomBytes(32).toString('hex');sessions.set(token,f.id);res.json({token,farmer:pub(f)})});
app.post('/api/auth/logout',auth,(req,res)=>{sessions.delete(req.token);res.json({ok:true})});
app.get('/api/records',auth,(req,res)=>{let a=req.db.records.filter(r=>r.farmerId===req.farmer.id);if(req.query.type){let qt=req.query.type;a=a.filter(r=>r.type===qt||(qt==='activity'&&r.type==='activitie'));}a.sort((x,y)=>y.date.localeCompare(x.date));res.json(a)});
app.post('/api/records',auth,(req,res)=>{let r={id:id(),farmerId:req.farmer.id,createdAt:new Date().toISOString(),type:req.body.type||'',date:req.body.date||'',field:req.body.field||'',crop:req.body.crop||'',activity:req.body.activity||'',input:req.body.input||'',expense:Number(req.body.expense)||0,harvest:req.body.harvest||'',quantity:Number(req.body.quantity)||0,unit:req.body.unit||'',season:req.body.season||'',notes:req.body.notes||''};if(!r.type||!r.date)return res.status(400).json({error:'Record type and date are required.'});req.db.records.push(r);write(req.db);res.json(r)});
app.delete('/api/records/:id',auth,(req,res)=>{let i=req.db.records.findIndex(r=>r.id===req.params.id&&r.farmerId===req.farmer.id);if(i<0)return res.status(404).json({error:'Record not found.'});req.db.records.splice(i,1);write(req.db);res.json({ok:true})});
app.put('/api/profile',auth,(req,res)=>{['name','email','village','district','state'].forEach(k=>{if(req.body[k]!==undefined)req.farmer[k]=String(req.body[k])});write(req.db);res.json({farmer:pub(req.farmer)})});
app.get('/api/summary',auth,(req,res)=>{let a=req.db.records.filter(r=>r.farmerId===req.farmer.id);res.json({records:a.length,fields:new Set(a.map(r=>r.field).filter(Boolean)).size,crops:new Set(a.map(r=>r.crop).filter(Boolean)).size,expenses:a.reduce((s,r)=>s+(+r.expense||0),0),harvestQuantity:a.reduce((s,r)=>s+(+r.quantity||0),0)})});
app.get('/api/ask',auth,(req,res)=>{let q=String(req.query.q||'').toLowerCase(),a=req.db.records.filter(r=>r.farmerId===req.farmer.id),t=q.split(/\s+/).filter(x=>x.length>2),e=a.filter(r=>t.some(x=>JSON.stringify(r).toLowerCase().includes(x)));if(!e.length)e=a.slice(0,8);let answer=`I found ${e.length} relevant record(s) in your personal farm history.`;if(/expense|cost|spend/.test(q))answer=`The matching records show total expenses of ₹${e.reduce((s,r)=>s+(+r.expense||0),0).toLocaleString('en-IN')}.`;if(/harvest|yield|production|quantity/.test(q))answer=`The matching records show a recorded quantity of ${e.reduce((s,r)=>s+(+r.quantity||0),0)} ${e[0]?.unit||'units'}.`;res.json({answer,evidence:e})});
['dashboard','fields','crops','activities','inputs','expenses','harvests','history','ask','reports','profile'].forEach(p=>app.get('/'+p,(req,res)=>res.sendFile(path.join(__dirname,'public/pages',p+'.html'))));app.get('/',(req,res)=>res.sendFile(path.join(__dirname,'public/index.html')));app.get('/login',(req,res)=>res.sendFile(path.join(__dirname,'public/login.html')));app.get('/register',(req,res)=>res.sendFile(path.join(__dirname,'public/register.html')));
app.listen(PORT,()=>console.log(`FarmTrace: http://localhost:${PORT}`));
